name: bookiee
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  pin_code_fields: ^8.0.1
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  syncfusion_flutter_pdfviewer: ^24.2.8
  syncfusion_flutter_gauges: ^24.2.9




  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  firebase_ui_auth: ^1.13.1
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.1
  get: ^4.3.8

  line_awesome_flutter: ^2.0.0
  flutter_screenutil: ^5.9.0
  animated_theme_switcher: ^2.0.10

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dynamic_curved_navigation_bar: ^0.0.2

  dynamic_height_grid_view: ^0.0.4
  flutter_grid_button: ^2.1.0

  flutter_native_splash: ^2.3.10

  dropdown_textfield: ^1.0.8
  drop_down_search_field: ^1.0.3
  dropdown_button2: ^2.3.9

  carousel_slider: ^4.2.1
  flutter_reorderable_grid_view: ^4.0.0
  griddelegate_fixedcrossaxiscount: ^0.0.1
  provider: ^6.1.2
  device_info_plus: ^9.1.2



  firebase_storage: ^11.7.4
  flutter_heatmap_calendar: ^1.0.5
  image_picker: ^1.1.0
  shared_preferences: ^2.2.3
  flutter_map_tile_caching: ^9.0.1
  tuple: ^2.0.2
  flutter_gradient_colors: ^2.1.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  raised_buttons: ^0.0.2
  file_picker: ^8.0.3
  timezone: ^0.9.3
  flutter_local_notifications: ^17.1.2
  settings_ui: ^2.0.2
  share: ^2.0.4







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/login_screen_pic.png
    - assets/User_Avatar.png
    - assets/icon/actionbook_icon.png
    - assets/icon/audiobook_icon.png
    - assets/icon/classics_icon.png
    - assets/icon/fiction_icon.png
    - assets/icon/Non-fictionbook_icon.png
    - assets/icon/google_icon.png
    - assets/icon/novelbook_icon.png
    - assets/icon/romancebook_icon.png
    - assets/icon/poetry_icon.png
    - assets/icon/crimefiction_book_icon.png
    - assets/icon/thrillerbook_icon.png
    - assets/google.png
    - assets/category/novel_banner.jpg
    - assets/category/fiction.jpg
    - assets/category/nonfiction.jpg
    - assets/category/romance.jpg
    - assets/category/crime-fiction.jpg
    - assets/category/thrillers.jpg
    - assets/category/poetry.jpg



